### ISSUE TITLE
Determinación de los eventos del reloj

### ISSUE THREAD

**Issue by NestorsImagination** [BurningFlower/time-reaver#12]
Determinar las anomalías aleatorias que ocurriran
- Reducir gravedad 50%
- Objetos de Background pasar a frontground
- Da la vuelta a la pantalla
- Disminuye un 50% la gravedad
- Crea varios objetos de puntos (es bueno)
- Cambia la camara de forma que el tio se mueve hacia la izquierda
- Se escribe una frase aleatoria en la pantalla
  - "Una vez me mate a mí mismo en el pasado, fue divertido."
  - "Si robas el futuro el presente será un rico bombón sin relleno."
  - "Es mejor vivir 10 años a través del tiempo que 100 años en una sola época."
  - "Lo primero es lo primero, pero no necesariamente en ese orden."
  - "No pierdas el tiempo. Entrégamelo y te cubriré de oro."
  - "Una vez pregunté la hora a un tipo con una ocarina, pero solo me gritó en contestación."
  - "He viajado años luz a través de los túneles del tiempo."
  - "Do not go gentle into that good night." (proposición de Jorge)
- Acelerar el tiempo un 1.25
- ¿Hacer ondulaciones en la pantalla?

**Comment by nRaiker** [comment]
Reducir gravedad 50% - resuelto
Objetos de Background pasar a frontground - resuelto
